# Use the official Node.js 22 image as the base image
FROM node:22-alpine

# Install OpenSSH Server
RUN apk update && apk add --no-cache openssh git bash

RUN npm install -g pm2 @angular/cli

# Create deploy user and group
RUN addgroup -S deploy && adduser -S -G deploy -s /bin/bash deploy
# Set password for deploy user (change 'deploypassword' to your desired password)
RUN echo -e "deploypassword\ndeploypassword" | passwd deploy
# Create app directory and set permissions
RUN mkdir -p /app && chown deploy:deploy /app

# Create hostkeys
RUN ssh-keygen -A

COPY ./keys/jenkins_deploy_key.pub /tmp/jenkins_deploy_key.pub
RUN mkdir -p /home/deploy/.ssh && \
    cat /tmp/jenkins_deploy_key.pub >> /home/deploy/.ssh/authorized_keys && \
    chown -R deploy:deploy /home/deploy/.ssh && \
    chmod 700 /home/deploy/.ssh && \
    chmod 600 /home/deploy/.ssh/authorized_keys && \
    rm /tmp/jenkins_deploy_key.pub



# Create app directory
WORKDIR /app

# Expose port for the application and SSH
EXPOSE 5000 22

# Start SSH service and the application
CMD ["/usr/sbin/sshd", "-D"]